### ISSUE TITLE
error when trying to connect

### ISSUE THREAD

**Issue by sheepdestroyer** [vanicat/hubic-swift#1]
Hi, I get the following error when trying to connect for the first time with your application :

```
./hubic-swift:117:in `connect_to_hubic': undefined method `forms' for #<Mechanize::File:0x000000018cbd28> (NoMethodError)
    from ./hubic-swift:179:in `main'
    from ./hubic-swift:187:in `<main>'
```

**Comment by sheepdestroyer** [comment]
OK,just pulled the last commit and now get the following :

```
unknown error, please fill a bug at
https://github.com/vanicat/hubic-swift/issues
with the following information:
code: 302
./hubic-swift:142:in `connect_to_hubic': undefined local variable or method `reponse' for main:Object (NameError)
    from ./hubic-swift:214:in `main'
    from ./hubic-swift:222:in `<main>'
```

**Comment by vanicat** [comment]
Arg, I made an error in my error reporting code. could you change the line 142, replacing `warn reponse` by `warn page.response`, or use the version I just push. I need the content of the response to now what is happening.

Sorry for the mistake.

**Comment by sheepdestroyer** [comment]
Because I kept `https://localhost.localdomain:4090/` in the code even though I set my app redirect uri as `https://127.0.0.1:4090` in Hubic app settings (hubic did not let me use the former and refused the input until I changed it to the latter...), i previously had this error : 

```
code: 302
reponse: {"set-cookie"=>"api.hubic.com=R411963662; path=/; expires=Thu, 31-Oct-2013 23:05:43 GMT", "date"=>"Tue, 29 Oct 2013 10:48:46 GMT", "server"=>"Apache", "location"=>"https://localhost.localdomain:4090/?error=invalid_request&error_description=please verify redirect uri&state=none", "content-length"=>"0", "keep-alive"=>"timeout=5, max=100", "connection"=>"Keep-Alive", "content-type"=>"text/plain"}
details: {"error"=>"invalid_request", "error_description"=>"please verify redirect uri", "state"=>"none"}
```

but now i changed the source to `https://127.0.0.1:4090` and get this new error : 

```
./hubic-swift:121:in `connect_to_hubic': undefined method `scan' for nil:NilClass (NoMethodError)
    from ./hubic-swift:215:in `main'
    from ./hubic-swift:223:in `<main>'
```

**Comment by vanicat** [comment]
Okay, this should work now.

Beware that once Hubic will solve some bug in their validation code for clients, I will use http://localost:3188/ as redirect URI (or something like that).

**Comment by sheepdestroyer** [comment]
updated but it failed once after asking my password as usual but now continues to fail without asking for the password anymore :

```
./hubic-swift list default
./hubic-swift:247:in `spawn': No such file or directory - swift (Errno::ENOENT)
    from ./hubic-swift:247:in `main'
    from ./hubic-swift:251:in `<main>'
```

**Comment by vanicat** [comment]
This is a wrapper around swift. It just log in hubic, then call swift. You need swift to do anything useful with it.

**Comment by sheepdestroyer** [comment]
yep sorry for that, I thought I had it installed before. I confirm it works now
