### ISSUE TITLE
no redirection from swift output on the command line?

### ISSUE THREAD

**Issue by sheepdestroyer** [vanicat/hubic-swift#2]
my upload is really slow to hubic, around 30Kb/s (I am in Japan with a Gigabit connection so don't know if the bottleneck could be set by OVH or be the peering through asia)

I tried to get around this limit with increasing `--object-threads` but no values seems to change the apparent ceiling of 30~40Ko/s

So to get more info on what is going on, I tried to run with `./hubic-swift upload -v --debug` which according to swift's help should "Show the curl commands of all http queries." but nothing prints on the cmdline... 

Does hubic-swift relay the output from swift?

**Comment by vanicat** [comment]
You have to give the `-v` and `--debug` argument before the command: `hubic-swift list --debug -v` do not show the curl command when `hubic-swift --debug -v list` does

**Comment by sheepdestroyer** [comment]
You were right and speed problem solved with --segment-threads (which seems to indicate that OVH put a thread limit at 30KB/s)

Thanks
