### ISSUE TITLE
error 509

### ISSUE THREAD

**Issue by szepeviktor** [vanicat/hubic-swift#9]
While using a [nodejs hubiC solution](https://github.com/gierschv/node-hubic-swiftauth) I was seeing 509s also.

```
/usr/lib/ruby/vendor_ruby/mechanize/http/agent.rb:268:in `fetch': 509 =>  (Mechanize::ResponseCodeError)
        from /usr/lib/ruby/vendor_ruby/mechanize.rb:1182:in `post_form'
        from /usr/lib/ruby/vendor_ruby/mechanize.rb:515:in `submit'
        from /usr/lib/ruby/vendor_ruby/mechanize/form.rb:178:in `submit'
        from /usr/lib/ruby/vendor_ruby/mechanize/form.rb:184:in `click_button'
        from ./hubic-swift:173:in `connect_to_hubic'
        from ./hubic-swift:244:in `main'
        from ./hubic-swift:252:in `<main>'
```

**Comment by Amoki** [comment]
Same problem here :'(

**Comment by vanicat** [comment]
If I understand corectly, if you use  nodejs hubiC solution, you don't need my app. You just have to directly use swift.

**Comment by szepeviktor** [comment]
Actually my chosen lib is this:
https://github.com/puzzle1536/hubic-wrapper-to-swift
It works without an HTTP server.

**Comment by ghost** [comment]
I found a workaround by adding sleep(2) just before page2=form.click_button (line 176). It works for me.
